language: go
go:
- 1.7.x
- 1.8.x
sudo: required
services:
  - docker
  - mongodb
  - redis-server
env:
  global:
  - secure: HCUb4CxhPlg74k5y8FSqX9AwDS6oK1/DFxNDJmnGzA9nEEmT0nPHVFP8IvvPdKTjealvTjzGHu6Y94IxfvCirlKqlLNVAXEh9hq4qz6gmnaeRuvEySB/Cni2lNzVbzavBP0npoD8WkDaeC4Vkh3YwInSQDnrlqKeBWeUdROA0cIqDG/h1RthGg1wmuFzdXxTw/VgrRnLocwgkftZwcR0jWq3jInEXikEOLFKA6BKTH8UZwt8esPkfsNDkmTo3u38iKaS8s9XPVEzmudH9oULCcjhA9q13trRpXNsSshqIGnfzshFrtUTADqlR+hA+9o73HcZ/UWot+r25rsJbTLKkcuu9EqobTDdbnzgmuyPoWe4RgjOobmHk69fx4J2SS+NkOLTUktf2MDPtmfrLtxytECDJdOJhElxRKsxzQT5PjrWoCzw9yTOPiE6p3oMbfHCaFyFcIRVocXMBq3/xZdN/OdU5sLmkPrfC24OKjLypc4RX3W76vWAnw2xxgeTAToLnx3wu87SyWs52uG56B2zFlqHSveHv4fOVqklTv+h+d5lVAuPLXfLx+YhVTAqvKzw77wa+Lk02CBYE9bPYf/U454e6m2VXMckOBmDOrhSjc3rviSAo4PRitQiCRMs6QE4aZJrZm0Aa5yKYECqHISZ3AO3Z/JoCAn/EYqHX1GgxGw=
  - secure: YYnwFw8J/NgzttoqwAtJiGwBtp10Cyld+11CzYheJDJxfQD64WyHRByhaPraUHcZAQfj12pYK2BxhHHHv5JreoyXtxkqH5y9s3aP8L/tDz2P2QT0AGP91xKptXEbhC2npl4myxVyYeWmxBf40yamvfnAFQAVfI87qRpadJcdIXWDFpSznVIA3K1UUJkweMgShK0PJLUvaQA1+mEKl6TM90Eb6dsfG5RNWhxRWZ4ORg4BXWOUvkjLfglCEewjmoa3WjONfU7+u41qP4MfntxPDn11IKCidOUIQQ1ya+n0LLdhEKL/0TPMaks8q7vdHG4+lWdcqcuUvp2KjTOEfs58mbCL4MbH4sVZFpyoUWLSg/6AWOwpdO3+f8M4FXxv1XBGIIY8we6p2HLzjuko4x1BBgyb7VaAOXtswn7yyfxNf86yYaQWL9UiMz44nS78sF/1fwfyC0ZripktsYnCGlRp7S/U81oALOMOUpQlDE+67qg9M7vFT2lt4C7Z1+L8wtzew8LgrvF7cr66XN3+gCxIPDZtO7PqNletFss0oaotewCUr8YfZnTfzQKJcC53Jzibpx1mTV40NmoJ0m+IBbZe9d0nHUZfTR0OvHdJ2+eU+JYGfl8i9mwYKplWAsiqLU81vop2jOKFXBYRh/Wljdyco9+bMuhN7sdTTnIdN0Yh8VM=
  - secure: kVExa0eE5pk7fI+xX/JctSlCgyxwRA3BvXBUQDMhto1jRyewBYDc5Pj/zjZJl5GN8FhdOqj4LXBeiN2KI9eGsJ4lpg3cjqfil/RKin7IQUh4bGPmdEswez0qdoHdowQ5X8jIDRDQxU4N5hDBGiN6JiurCQ8C07eHkAvAzBSejkLkw+R+YCRN1fBvgA1GhUntGuwqS8pUAHMGtzlrDc3Sbu4UTgDX8isf/srOdUF8KjaMYyRovyaqbl2QPT+DS4TMC9dwXIl1SEKHIYJOOSjt3W/4hHr1zcAtfE/EqsHrzoO5AizKEdLInbytFsPLd8Ullo5VmLuw/cTtujDhIC0ws8G3L59YgJesOK1vZMXoFPDkUeAklgqQY7ciCF4P6nws/23oQ1No5wkNruvb0NlTl+4Q2mKIknetGJ+SUIytAr/6IfnlhlCvt3eOQxvfWVPXIDgbechnbKxWJnUAcl5VVO7duZXClSSHi4bmfztPiBn+Ea2rbDSohvRvlr/W5Th/Ycjon3rB0iXeeqYhzdvTpDI7MDKoCISCvGn3PvfVFNgy7RZBcupcroywwQfpsis74tp1P3RptRYGZiEA0+sBOXn6BR+jzPylPGFH2C7EVUSCE8Ed2Hgc29DOcd1c1PSe/QiAUxPvnq8dOR7lnLuahcSWkdiBnyGGRVa3uLueLkY=
  - REPO=swatlabs/godataberus
  - VERSION=0.0.1
  - COMMIT=${TRAVIS_COMMIT::8}
  - GLIDE_VERSION=0.12.3
install:
  - wget "https://github.com/Masterminds/glide/releases/download/v${GLIDE_VERSION}/glide-v${GLIDE_VERSION}-linux-amd64.tar.gz"
  - mkdir -p $HOME/bin
  - tar -vxz -C $HOME/bin --strip=1 -f glide-v${GLIDE_VERSION}-linux-amd64.tar.gz
  - export PATH="$HOME/bin:$PATH"
before_script:
  - make clean
script:
  - make vet
  - make fmt
  - make lint
  - make check test tests
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker build -t $REPO:$VERSION -f Dockerfile .;
      docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD;
      docker push $REPO:$VERSION;
    fi
notifications:
  email:
    recipients:
    - theswatlabs@gmail.com
    on_success: change
    on_failure: always
