language: go
go:
- 1.7.x
- 1.8.x
sudo: required
services:
  - docker
  # - mongodb
env:
  global:
  - secure: kgtZBCmfuhxCfq16Q6M6YpQ1C0VfvZghEyhkj7UjqBkkfn92F2kzMKA9o9qgKa3r/uKw08hb4ic/FIau8WHhv+0yZrVSu8XhRyPjW3Hmp/BXl6gZ/Ksm4QGj/wx4Hve9WKlfTx0m6IRFmosszlttM25flJjqW7yI04KExnO4qdlubg6cc3aSpWyQLbsYrSiZzWwCExYYOsw+bqbPYzJq5/cItGOZIi1pkU4aieZj0pV1eguoUaYebABzzz20nfCJXLShlHFmaptVnhJdRmIgEzVUOmrb4BrRgzkwok8QUg1Ki9ntN79rW9UY3nbYjoOEVIKc/EWNjxZltQleAUqMac7R8XDNtvCesQw6hYec1ig0Vxr2IriGex/SVMmhXEQyM2RHf4T95EicPPZ1ZNe91b5kx5j69O0WEoBt79+blnaz85w6qYG6D6CIkuKs7ikhOOvZOUouhmY97bPdg/XUI8ngK32sRTAyjWORgV27R4zsCPyZxFA3mZZFQ94KZ0K335A7mo8d5/Dwcoe+ZpXkg4DkId+6J/9W1XjPX7wyd/O8RdDYHl+8Mm1JAZNHhOloHTOdoVfptYSUuwKbjFlHB16jtHzZtNdsuYzAdmKgym94nBKnvN16apDktinIW6DKtZZYKJBGNf4aEp75SzwJGO92/ThFKMjUHEvouB9rN+I=
  - secure: CzbJG8BMu3fzcR0ic0DlgkdwRVUtq2MRKLMr29oTeLFJynyPPGhgaHCwHePrGFpA5D26XHVYXOMbX7NNXt2XwkTl+ugHQL2s9ZAnOYJSM425S/L/bfCAAjcIhNFdULxEsJMc2WWwcN0HYmmZSaTlQo5e7Xze0qdIMKVKPFYRZLceZ4E8erEckj5/+Ipcp1VkbU+i/1bjyVLB5SMCml+Y6712xCXJHqXd/hFem2+0cts7uBMCpmtk4/PJAMb+vFQyEdHojonXR/8s6wlGhiJNtZTNS/9zhB3fn/AEIjNKHTrPYjztiapqMmJD/nH2H2ByNWPwz3yQ1c5sp6Is1a4+f2shGgdo8E8tR9s3BIZRrAHgcLZW+19eOC2RIOS3TPNy+P81BfF7zG8jiVi92lwG7MytLDUzMc8dr3zsZ2vsB97UmK0Ys7wbno+wLbPEnqE0a7AYQmHe5fsYQ8tb+Fy1u6LbHHtsHF7m0Kayhw8Fne3TZmcdOJiqZas7Js33Lm5ysb3tv6P7piHHiFAoRKijulr57Sb5TYEnOFWVUVrfY8r49O28OOboFa+sT1FORS6cMZK22NE/z8vfbUdOqPZTitXwljQiY+ugf8Frz1AfE1v8Oewqm/PAMw6jj2Tif468fVhVD3UWjPLrMbq8mdMRSt6XYcNpH9m2ZwbRFmYwxbc="
  - secure: rg6glpu1EE3GFRx18kHmbN/XP/krb9X9QahK6SSTSahYVqcmHiOZ2Fv0XAMUXpisnu2Nue5GXS0BXVdxfCN/pHQUH9ZxEtKmJNwwnv8Gu+db3+E400D8uParArX4NriVk3CEbYEEG20r7F6vRWR7KUhgMtMlEJWDSvap/IWT2OWyliQvL9t1S8gVirgtR8JqDsVyajx8/6i3jx8ZihmivowS035ObsOeu4ChDEgHZP5welUrltRMRtBRDP0eKp4f32JCMyD+Fb6LYdmpXzvuktgm6dufPaNyOrwdE91dinv0qOiVuYU5OajtXpGJZuOqpvdT0pYxrnDx5pazqRTyPRvei64Mf3mg0qqpJSiw39rorODZdrSA/D+uuiuxvPvfScjTK+tj2DbBHbfclogVn8Lky4tMO0smoD3wQ/Iyy+cBv0m+pf6SS01c3DM9HM/zFXE/xkrBNKoG+UBi6eusPfBIuKynJn8VumTl9BYcsdOWDlMB45d7pPw1UE7o1CREEcsLDd2TjQ9B7EPqJ2SZyQvmhG1SHPa3JBfhTeE+5mntEPNYmCcH0EpeRA0Pd9FUNGzR40wf5wjOq5TkqooZpMxV9z56XN1tF7IYW+dtvETDA0jBVteCANVR2/mKW1lUau5Sn5QKd5G2raOhcltjVkg7LN3SZpfktqsIhtQVtrA=
  - REPO=swatlabs/godataberus
  - VERSION=0.0.1
  - COMMIT=${TRAVIS_COMMIT::8}
  - GLIDE_VERSION=0.12.3
install:
  - wget "https://github.com/Masterminds/glide/releases/download/v${GLIDE_VERSION}/glide-v${GLIDE_VERSION}-linux-amd64.tar.gz"
  - mkdir -p $HOME/bin
  - tar -vxz -C $HOME/bin --strip=1 -f glide-v${GLIDE_VERSION}-linux-amd64.tar.gz
  - export PATH="$HOME/bin:$PATH"
before_script:
  - make clean
script:
  - make vet
  - make fmt
  - make lint
  - make check test tests
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker build -t $REPO:$VERSION -f Dockerfile .;
      docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD;
      docker push $REPO:$VERSION;
    fi
notifications:
  email:
    recipients:
    - theswatlabs@gmail.com
    on_success: change
    on_failure: always
